/*
 * File: app/store/Locations.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CheckOut.store.Locations', {
    extend: 'Ext.data.Store',
    
    requires: [
        'CheckOut.model.Location'
    ],

    config: {
        sorters: {
            property: 'time',
            direction: 'DESC'
        },
        pageSize: 500,
        model: 'CheckOut.model.Location',
        proxy: {
            type: "sql"
        },
        storeId: 'Locations'
    }
});